name: Faz push

on:
  pull_request:
    branchs:
      - 'feature/**'
      - 'hotfix/**'
      - 'release/**'

jobs:
  push:
    name: Push
    runs-on: ubuntu-20.04

    steps:
    - name: Coleta variáveis de ambiente
      run: |
        echo "::set-output name=REGISTRY::$(make print-GITHUB_REGISTRY)"
        echo "::set-output name=IMAGE_NAME::$(make print-IMAGE_NAME)"
        echo "::set-output name=IMAGE_TAG_DEV::$(make print-IMAGE_TAG_DEV)"
        echo "::set-output name=IMAGE_TAG_PROD::$(make print-IMAGE_TAG_PROD)"
      shell: bash
      id: environment

    # Podman Login action (https://github.com/redhat-actions/podman-login) also be used to log in,
    # in which case 'username' and 'password' can be omitted.
    - name: Faz push para registry da imagem de dev
      id: push-to
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.environment.outputs.IMAGE_NAME }}
        registry: ${{ steps.environment.outputs.REGISTRY }}
        tags: ${{ steps.environment.outputs.IMAGE_TAG_DEV }}
    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"

    - name: Faz push para registry da imagem de prod
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.environment.outputs.IMAGE_NAME }}
        registry: ${{ steps.environment.outputs.REGISTRY }}
        tags: ${{ steps.environment.outputs.IMAGE_TAG_PROD }}
    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
