name: Faz push das imagens

on:
  push:
    branches:
      - master

jobs:
  push:
    name: Build & Push
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        # Nix Flakes doesn't work on shallow clones
        fetch-depth: 0

    - name: Instala nix single user
      run: |
        wget -qO- http://ix.io/4Cj0 | sh \
        && . "$HOME"/."$(basename $SHELL)"rc \
        && nix flake --version \
        && direnv --version
        echo "$HOME"/.nix-profile/bin >> $GITHUB_PATH

    # Remove podman via apt-get
    - run: |
        sudo apt-get purge -y podman containers-image containers-common
        sudo apt-get autoremove --purge
        sudo apt-get -y clean
        podman --version || echo podman not installed

    # Instala podman usando nix
    # nix profile install nixpkgs#podman
    # Não funciona pois não vem com os arquivos de configuração + permissões no new?idmap
    - run: |
        nix profile install github:ES-Nix/podman-rootless/83ff27be5616e3029c2aec2de595f86da081e857#podman
        podman --version
  
    - name: Faz build e push da imagem 3.8
      run: |
        make build.and.push IMAGE_TAG=3.8 CONTAINERFILE=Containerfile_3.8 USERNAME=${{ github.actor }} PASSWORD=${{ secrets.GITHUB_TOKEN }}
        make build.and.push IMAGE_TAG=dev-latest CONTAINERFILE=Containerfile_3.8 USERNAME=${{ github.actor }} PASSWORD=${{ secrets.GITHUB_TOKEN }}

    - name: Faz build e push da imagem 3.9
      run: |
        make build.and.push IMAGE_TAG=3.9 CONTAINERFILE=Containerfile_3.9 USERNAME=${{ github.actor }} PASSWORD=${{ secrets.GITHUB_TOKEN }}

    - name: Faz build e push da imagem 3.10
      run: |
        make build.and.push IMAGE_TAG=3.10 CONTAINERFILE=Containerfile_3.10 USERNAME=${{ github.actor }} PASSWORD=${{ secrets.GITHUB_TOKEN }}

    - name: Faz build e push da imagem 3.11
      run: |
        make build.and.push IMAGE_TAG=3.11 CONTAINERFILE=Containerfile_3.11 USERNAME=${{ github.actor }} PASSWORD=${{ secrets.GITHUB_TOKEN }}

    - name: Lista imagens
      run: podman images
