name: Test builds

on:
  push:

#on:
#  pull_request:
#    branchs:
#      - 'feature/**'
#      - 'hotfix/**'
#      - 'release/**'

jobs:
  build-dev:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Prints podman --version
        run: podman --version

      - name: Build dev OCI image
        run: make dev.build

      - name: Saves dev OCI image
        run: podman save --format docker-archive --output /tmp/image.tar.gz localhost/imobanco/python:dev-latest

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Load image
        run: |
          docker load < /tmp/image.tar

      - name: Build OCI image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            docker.pkg.github.com/imobanco/python:dev-latest

  build-prod:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Build prod
        run: make prod.build
