name: Test builds


on:
  pull_request:
    branchs:
      - 'feature/**'
      - 'hotfix/**'
      - 'release/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        # Nix Flakes doesn't work on shallow clones
        fetch-depth: 0

    - uses: cachix/install-nix-action@v13
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
        extra_nix_config: |
          experimental-features = nix-command flakes ca-references ca-derivations
          sandbox = false
    - run: nix flake --version
#    - run: nix flake metadata nixpkgs

    # Remove podman via apt-get
    - run: |
        sudo apt-get purge -y podman containers-image containers-common
        sudo apt-get autoremove --purge
        sudo apt-get -y clean
        podman --version || echo podman not installed

    # Instala podman usando nix
    - run: nix profile install github:ES-Nix/podman-rootless/6a498059fc8a120ecc2f0d8e3712f43256c4ee1d
    # Não funciona pois não vem com os arquivos de configuração
#    - run: nix profile install nixpkgs#podman
    - run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends --no-install-suggests -y uidmap
    - run: podman --version
#    - run: podman info --debug

    - name: Faz build da imagem de dev usando podman via nix
      run: |
        make build
        echo "::set-output name=REGISTRY::$(make print-GITHUB_REGISTRY)"
        echo "::set-output name=IMAGE_NAME::$(make print-IMAGE_NAME)"
        echo "::set-output name=IMAGE_TAG_DEV::$(make print-IMAGE_TAG_DEV)"
      shell: bash
      id: dev-build

    - name: Faz build da imagem de prod usando podman via nix
      run: |
        make build.prod
        echo "::set-output name=REGISTRY::$(make print-GITHUB_REGISTRY)"
        echo "::set-output name=IMAGE_NAME::$(make print-IMAGE_NAME)"
        echo "::set-output name=IMAGE_TAG_PROD::$(make print-IMAGE_TAG_PROD)"
      shell: bash
      id: prod-build

    - name: Lista imagens
      run: podman images
