name: Test builds

## Útil quando debugando.
#on:
#  push:

on:
  pull_request:
    branchs:
      - 'feature/**'
      - 'hotfix/**'
      - 'release/**'

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        # Nix Flakes doesn't work on shallow clones
        fetch-depth: 0

    - uses: cachix/install-nix-action@v13
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
        extra_nix_config: |
          experimental-features = nix-command flakes ca-references ca-derivations
          sandbox = false
    - run: nix flake --version
#    - run: nix flake metadata nixpkgs

    # Remove podman via apt-get
    - run: |
        sudo apt-get purge -y podman containers-image containers-common
        sudo apt-get autoremove --purge
        sudo apt-get -y clean
        podman --version || echo podman not installed

    # Instala podman usando nix
    - run: nix profile install github:ES-Nix/podman-rootless/6a498059fc8a120ecc2f0d8e3712f43256c4ee1d
    # Não funciona pois não vem com os arquivos de configuração
#    - run: nix profile install nixpkgs#podman
    - run: sudo apt-get update && sudo apt-get install -y uidmap
    - run: podman --version
#    - run: podman info --debug

    - name: Faz build da imagem de dev usando podman via nix
      run: |
        make dev.build
        echo "::set-output name=REGISTRY::$(make print-GITHUB_REGISTRY)"
        echo "::set-output name=IMAGE_NAME::$(make print-IMAGE_NAME)"
        echo "::set-output name=IMAGE_TAG::$(make print-IMAGE_TAG)"
      shell: bash
      id: build

    - name: Log in to Quay.io
      uses: redhat-actions/podman-login@v1
      with:
          registry: ${{ steps.build.outputs.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    # Podman Login action (https://github.com/redhat-actions/podman-login) also be used to log in,
    # in which case 'username' and 'password' can be omitted.
    - name: Push to
      id: push-to
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build.outputs.IMAGE_NAME }}
        registry: ${{ steps.build.outputs.REGISTRY }}
        tags: ${{ steps.build.outputs.IMAGE_TAG }}
    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"

  build-prod:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Build prod
        run: make prod.build
